ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2026 4 8 14 7 47)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright Â© Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "24pTIMESNEWROMANBOLD"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 333.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 700)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "11pTIMESNEWROMANBOLD"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 153.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 700)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "-1p"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "")
      (fontHeight -14.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "16pTIMESNEWROMANBOLD"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 222.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 700)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "20pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 278.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "G431_Nucleo_1_N"
    (originalName "G431_Nucleo_1_N")
    (pin (pinNum 1)  (pt -500 700) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 700) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 700) "PA9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -500 600) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 600) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 600) "PA10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -500 500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 500) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 500) "NRST" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt -500 400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 400) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 400) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -500 300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 300) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 300) "PA12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt -500 200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 200) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 200) "PB0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt -500 100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 100) "7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 100) "PB7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt -500 0) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 0) "8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 0) "PA15" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt -500 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -100) "9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -100) "PB6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt -500 -200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -200) "10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -200) "PF0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt -500 -300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -300) "11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -300) "PF1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt -500 -400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -400) "12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -400) "PA8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt -500 -500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -500) "13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -500) "PA11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt -500 -600) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -600) "14" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -600) "PB5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt -500 -700) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -700) "15" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -500 -700) "PB4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 500 700) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 700) "16" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 700) "VIN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 500 600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 600) "17" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 600) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 500 500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 500) "18" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 500) "NRST" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt 500 400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 400) "19" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 400) "5V" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 500 300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 300) "20" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 300) "PA2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 21)  (pt 500 200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 200) "21" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 200) "PA7" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 22)  (pt 500 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 100) "22" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 100) "PA6(PA15)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 23)  (pt 500 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 0) "23" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 0) "PA5(PB7)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 24)  (pt 500 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -100) "24" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -100) "PA4" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 25)  (pt 500 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -200) "25" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -200) "(PA3)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 26)  (pt 500 -300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -300) "26" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -300) "PA1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 27)  (pt 500 -400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -400) "27" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -400) "PA0" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 28)  (pt 500 -500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -500) "28" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -500) "AVDD" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 29)  (pt 500 -600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -600) "29" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -600) "3V3" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 30)  (pt 500 -700) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -700) "30" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -700) "PB3/(PB8)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -450 -800) (pt -450 800) (width 10) )
    (line (pt -450 -800) (pt 550 -800) (width 10) )
    (line (pt -450 800) (pt 550 800) (width 10) )
    (line (pt 550 800) (pt 550 -800) (width 10) )
    (text  (pt -400 800) "NUCLEO-G431KB" (textStyleRef "10pTIMESNEWROMAN") (extent 0.0 0.0) )
    (attr "RefDes" ""  (pt -450 900) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -450 -900) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "CONDENSATEUR_POL_ELECTROLY_R15"
    (originalName "CONDENSATEUR_POL_ELECTROLY_R15")
    (pin (pinNum 1)  (pt 0 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 0) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 0) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 30 -80) (pt 30 80) (width 10) )
    (line (pt 0 0) (pt 30 0) (width 10) )
    (line (pt 100 0) (pt 70 0) (width 10) )
    (line (pt 0 50) (pt -40 50) (width 10) )
    (line (pt -20 30) (pt -20 70) (width 10) )
    (line (pt 70 -80) (pt 70 80) (width 10) )
    (attr "RefDes" ""  (pt -50 90) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -120 90) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Value" "10µF/>25V"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Type" "POL_RAD_2.0/5.08"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "CONDENSATEUR_POL_ELECTROLY_R12"
    (originalName "CONDENSATEUR_POL_ELECTROLY_R12")
    (pin (pinNum 1)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 -100) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 -100) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 -100) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -180) (pt 0 -20) (width 10) )
    (line (pt 40 -100) (pt 100 -100) (width 10) )
    (arc (pt 200 -100) (radius 160) (startAngle 151) (sweepAngle 29) (width 10))
    (arc (pt 200 -100) (radius 160) (startAngle 180) (sweepAngle 29) (width 10))
    (line (pt -30 -50) (pt -70 -50) (width 10) )
    (line (pt -50 -70) (pt -50 -30) (width 10) )
    (attr "RefDes" ""  (pt -50 90) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -120 90) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Value" "10µF/>25V"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Type" "POL_RAD_2.0/5.08"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "REGULATEUR_TO220_78XX_1_N"
    (originalName "REGULATEUR_TO220_78XX_1_N")
    (pin (pinNum 1)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -100 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "IN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 300 -300) (rotation 270.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 300 -400) "2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -300) "GND" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 600 -100) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 700 -100) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -100) "OUT" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -300) (pt 0 0) (width 10) )
    (line (pt 0 -300) (pt 600 -300) (width 10) )
    (line (pt 0 0) (pt 600 0) (width 10) )
    (line (pt 600 0) (pt 600 -300) (width 10) )
    (text  (pt 200 -280) "GND" (textStyleRef "10pTIMESNEWROMAN") (extent 0.0 0.0) )
    (attr "RefDes" ""  (pt 0 0) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -220 0) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" "7805"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Package" "(TO220)"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "CONDENSATEUR_CER_RAD_5.08_1_N"
    (originalName "CONDENSATEUR_CER_RAD_5.08_1_N")
    (pin (pinNum 1)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 -100) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 -100) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 -100) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 70 -20) (pt 70 -180) (width 10) )
    (line (pt 30 -180) (pt 30 -20) (width 10) )
    (line (pt 0 -100) (pt 30 -100) (width 10) )
    (line (pt 100 -100) (pt 70 -100) (width 10) )
    (attr "RefDes" ""  (pt -10 -10) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -120 -10) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Value" "100nF"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Type" "RADIAL_5.08"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "CONDENSATEUR_POL_ELECTROLY_RB9"
    (originalName "CONDENSATEUR_POL_ELECTROLY_RB9")
    (pin (pinNum 1)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 -100) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 -100) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 -100) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 30 -180) (pt 30 -20) (width 10) )
    (line (pt 0 -100) (pt 30 -100) (width 10) )
    (line (pt 100 -100) (pt 70 -100) (width 10) )
    (line (pt 0 -50) (pt -40 -50) (width 10) )
    (line (pt -20 -70) (pt -20 -30) (width 10) )
    (line (pt 70 -180) (pt 70 -20) (width 10) )
    (attr "RefDes" ""  (pt -50 -10) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -120 -10) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Value" "4.7µF/63V"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Type" "POL_RAD_2.54/5.08"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "CONDENSATEUR_POL_ELECTROLY_RBE"
    (originalName "CONDENSATEUR_POL_ELECTROLY_RBE")
    (pin (pinNum 1)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 -100) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 -100) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 -100) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -180) (pt 0 -20) (width 10) )
    (line (pt 40 -100) (pt 100 -100) (width 10) )
    (arc (pt 200 -100) (radius 160) (startAngle 151) (sweepAngle 29) (width 10))
    (arc (pt 200 -100) (radius 160) (startAngle 180) (sweepAngle 29) (width 10))
    (line (pt -30 -50) (pt -70 -50) (width 10) )
    (line (pt -50 -70) (pt -50 -30) (width 10) )
    (attr "RefDes" ""  (pt -50 -10) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -120 -10) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Value" "4.7µF/63V"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Type" "POL_RAD_2.54/5.08"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "DOUILLE_BANANE_4mm_1_N"
    (originalName "DOUILLE_BANANE_4mm_1_N")
    (pin (pinNum 1)  (pt 0 0) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -150 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (arc (pt 100 0) (radius 100) (startAngle 0) (sweepAngle 360) (width 10))
    (arc (pt 100 0) (radius 50) (startAngle 0) (sweepAngle 360) (width 10))
    (attr "RefDes" ""  (pt 0 100) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -320 100) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" "BANANE_4mm"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "ECRAN_TFT_2.4_TACTILE_1_N"
    (originalName "ECRAN_TFT_2.4_TACTILE_1_N")
    (pin (pinNum 1)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "VCC" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 0 -200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -200) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -200) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 0 -300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -300) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -300) "CS" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 0 -400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -400) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -400) "RESET" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 0 -500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -500) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -500) "D/C" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 0 -600) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -600) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -600) "MOSI" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 0 -700) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -700) "7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -700) "SCK" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 0 -800) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -800) "8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -800) "LED" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 0 -900) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -900) "9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -900) "MISO" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 0 -1000) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -1000) "10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -1000) "T_CLK" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 0 -1100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -1100) "11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -1100) "T_CS" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 0 -1200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -1200) "12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -1200) "T_DIN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 0 -1300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -1300) "13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -1300) "T_DOUT" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 0 -1400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -1400) "14" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -1400) "T_IRQ" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 900 -400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -400) "18" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -400) "SD_CS" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 900 -500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -500) "17" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -500) "SD_MOSI" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 900 -600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -600) "16" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -600) "SD_MISO" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 900 -700) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -700) "15" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -700) "SD_SCK" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -1500) (pt 0 0) (width 10) )
    (line (pt 0 -1500) (pt 900 -1500) (width 10) )
    (line (pt 0 0) (pt 900 0) (width 10) )
    (line (pt 900 0) (pt 900 -1500) (width 10) )
    (text  (pt 200 0) "TFT 2.4 TOUCH" (textStyleRef "10pTIMESNEWROMAN") (extent 0.0 0.0) )
    (attr "RefDes" ""  (pt 0 100) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 0 -1600) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Goutte_Strap_1_N"
    (originalName "Goutte_Strap_1_N")
    (pin (pinNum 1)  (pt 50 0) (rotation 0.0) (isFlipped False) (pinLength 150)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 125 0) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 50 0) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -50 0) (rotation 180.0) (isFlipped False) (pinLength 150)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -125 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -80 -40) (pt -80 40) (width 10) )
    (line (pt -80 -40) (pt -20 -40) (width 10) )
    (line (pt -80 40) (pt -20 40) (width 10) )
    (line (pt -20 40) (pt -20 -40) (width 10) )
    (line (pt 20 -40) (pt 20 40) (width 10) )
    (line (pt 20 -40) (pt 80 -40) (width 10) )
    (line (pt 20 40) (pt 80 40) (width 10) )
    (line (pt 80 40) (pt 80 -40) (width 10) )
